# Travis yml file inspired by scikit-bio
# Check on http://lint.travis-ci.org/ after modifying it!
sudo: false
language: python
env:
  - PYVERSION=3.5 USE_CYTHON=TRUE MAKE_DOC=TRUE
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda info -a
install:
  - wget -q https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml
  - conda env create -q -n test-env --file qiime2-latest-py36-linux-conda.yml
  - conda install --yes -n test-env --file ci/conda_requirements.txt -c biocore
  - conda install --yes -n test-env cython
  - source activate test-env
  - pip install -r ci/pip_requirements.txt
  - pip install numpy
  - pip install -e .
  - sudo pip install flake8
  - sudo pip install nose
  - sudo pip install coveralls
script:
  - source activate test-env
  - flake8 bacdive setup.py
  - nosetests -v bacdive --with-coverage --cover-package=bacdive
after_success:
  - coveralls
